### ISSUE TITLE
how do i flash this onto my kyria

### ISSUE THREAD

**Issue by ed-aka-yaboi** [andrewjrae/kyria-keymap#3]

**Comment by andrewjrae** [comment]
To get the entire keymap as is, with its RSTHD alpha layer and all, the easiest thing to do is follow the setup guide [here](https://docs.qmk.fm/#/newbs_building_firmwarel). Use this to create a new keymap for the kyria, then delete the folder that was created, and clone this repository so it replaces the directory you deleted.
