### ISSUE TITLE
snake case and capsword won't work on a preonic

### ISSUE THREAD

**Issue by aluminum-ice** [andrewjrae/kyria-keymap#4]
I've gotten this to work on my gmmk pro but on my preonic it fails. For example, turning on capsword becomes a permanent caps that does not terminate when you press space and snake case doesn't turn on at all. Have you seen this before?

**Comment by andrewjrae** [comment]
I have not, I'm surprised that it seems to be board dependent. Could you perhaps link your keymap?

**Comment by aluminum-ice** [comment]
I had a mistake in my code! I caught it when I reviewed your sample code. Thank you for a great set of features!

**Comment by andrewjrae** [comment]
Awesome, glad you got it all sorted out, and I'm happy you enjoy the features :)
